@baseUrl=http://localhost:3001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjY3ODkyNzA1LCJleHAiOjE2Njc5NzkxMDV9.xA7rnZDzUzQYJSwYg3QwPKh1QSR-NZ_T1HS-7TO5xhk
### User requests
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Jhonny English",
  "email": "JhonnyEng@gmail.com",
  "password": "Jhonny"
}
###User details
GET {{baseUrl}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}


### User login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "Devilman@gmail.com",
  "password": "Devilman"
}

###Room Type requests
POST {{baseUrl}}/roomTypes
Content-Type: application/json

{
  "name":"test"
}
###
GET {{baseUrl}}/roomTypes
###
GET {{baseUrl}}/roomTypes/3
###
PUT {{baseUrl}}/roomTypes/3
Content-Type: application/json

{
  "name":"test3"
}
###
DELETE {{baseUrl}}/roomTypes/4
###

###Room requests
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name":"test",
  "roomTypeId": 1
}
###